name: musik
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.9
  flutter_modular: 1.2.5+1
  cupertino_icons: ^0.1.3
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
